In [689]:
import pandas as pd

In [690]:
df=pd.read_csv('Task_3_and_4_Loan_Data.csv')

In [691]:
df

,customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default
0,8153374,0,5221.5452,3915.4712,78039.3855,5,605,0
1,7442532,5,1958.9287,8228.7525,26648.4352,2,572,1
2,2256073,0,3363.0093,2027.8309,65866.7125,4,602,0
3,4885975,0,4766.6480,2501.7304,74356.8835,5,612,0
4,4700614,1,1345.8277,1768.8262,23448.3263,6,631,0
...,...,...,...,...,...,...,...,...
9995,3972488,0,3033.6471,2553.7331,42691.6279,5,697,0
9996,6184073,1,4146.2393,5458.1635,79969.5052,8,615,0
9997,6694516,2,3088.2237,4813.0909,38192.6759,5,596,0
9998,3942961,0,3288.9017,1043.0997,50929.3721,2,647,0
9999,5533570,1,1917.6525,3050.2482,30611.6282,6,757,0

In [692]:
pd.set_option('display.float_format', lambda x: f'{x:.4f}')

In [693]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
customer_id,10000.0000,4974576.9975,2293889.7060,1000324.0000,2977661.0000,4989501.5000,6967210.2500,8999789.0000
credit_lines_outstanding,10000.0000,1.4612,1.7438,0.0000,0.0000,1.0000,2.0000,5.0000
loan_amt_outstanding,10000.0000,4159.6770,1421.3991,46.7840,3154.2354,4052.3772,5052.8981,10750.6778
total_debt_outstanding,10000.0000,8718.9168,6627.1648,31.6527,4199.8360,6732.4072,11272.2637,43688.7841
income,10000.0000,70039.9014,20072.2141,1000.0000,56539.8679,70085.8263,83429.1661,148412.1805
years_employed,10000.0000,4.5528,1.5669,0.0000,3.0000,5.0000,6.0000,10.0000
fico_score,10000.0000,637.5577,60.6579,408.0000,597.0000,638.0000,679.0000,850.0000
default,10000.0000,0.1851,0.3884,0.0000,0.0000,0.0000,0.0000,1.0000

In [694]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               10000 non-null  int64
 1   credit_lines_outstanding  10000 non-null  int64
 2   loan_amt_outstanding      10000 non-null  float64
 3   total_debt_outstanding    10000 non-null  float64
 4   income                    10000 non-null  float64
 5   years_employed            10000 non-null  int64
 6   fico_score                10000 non-null  int64
 7   default                   10000 non-null  int64
dtypes: float64(3), int64(5)
memory usage: 625.1 KB

In [695]:
df.isna().sum()

customer_id                 0
credit_lines_outstanding    0
loan_amt_outstanding        0
total_debt_outstanding      0
income                      0
years_employed              0
fico_score                  0
default                     0
dtype: int64

In [696]:
x=df.select_dtypes(include='number').columns

In [697]:
x=x.drop('customer_id')
x=x.drop('default')
x=df[x]

In [698]:
y=df['default']

## Ml Exp

##### Exp1.1

In [699]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=24,test_size=0.20,stratify=y)

In [700]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [701]:
model.coef_

array([[ 7.25382902e+00,  4.27578538e-04,  1.42728397e-03,
        -3.10370492e-04, -2.83806469e+00, -3.34073736e-02]])

In [702]:
def feature_elaborate(x,model):
    for each in range(len(x.columns)):
        print(f'the one unit of {x.columns[each]} increase has this rate of change in prediction {model.coef_.flatten()[each]}')

In [703]:
feature_elaborate(x=x_train,model=model)

the one unit of credit_lines_outstanding increase has this rate of change in prediction 7.253829015699976
the one unit of loan_amt_outstanding increase has this rate of change in prediction 0.0004275785378079674
the one unit of total_debt_outstanding increase has this rate of change in prediction 0.0014272839724986425
the one unit of income increase has this rate of change in prediction -0.00031037049223333674
the one unit of years_employed increase has this rate of change in prediction -2.838064686122671
the one unit of fico_score increase has this rate of change in prediction -0.03340737359537556

In [704]:
predict_prob=model.predict_proba(x_test)

In [705]:
temp_new_customer=pd.DataFrame({"credit_lines_outstanding": [2],"loan_amt_outstanding": [5000],"total_debt_outstanding": [9000],"income": [65000],"years_employed": [4],"fico_score": [620]
})

In [706]:
pr=model.predict_proba(temp_new_customer)[:,1]

In [707]:
print(pr)

[8.98894452e-07]

In [708]:
print(pr.round())

[0.]

In [709]:
print(model.coef_)
print(model.intercept_)

[[ 7.25382902e+00  4.27578538e-04  1.42728397e-03 -3.10370492e-04
  -2.83806469e+00 -3.34073736e-02]]
[8.82570658]

In [710]:
print(model.predict_proba(x_test[:10]))

[[1.00000000e+00 1.63327017e-11]
 [1.00000000e+00 4.89618003e-13]
 [9.99880736e-01 1.19264237e-04]
 [9.65941152e-01 3.40588483e-02]
 [9.84884683e-01 1.51153168e-02]
 [1.00000000e+00 8.37552153e-17]
 [1.00000000e+00 3.63924662e-10]
 [9.99999999e-01 1.22989597e-09]
 [1.00000000e+00 1.86855348e-13]
 [1.00000000e+00 1.36539991e-19]]

In [711]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

y_pred = model.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("ROC AUC:", roc_auc_score(y_test, model.predict_proba(x_test)[:,1]))

Accuracy: 0.998
[[1629    1]
 [   3  367]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1630
           1       1.00      0.99      0.99       370

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

ROC AUC: 0.9999900514010943

In [712]:
predict_prob.min()

np.float64(0.0)

In [713]:
predict_prob.max()

np.float64(1.0)

##### Exp1.2 with scaling

In [714]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_ss_train=ss.fit_transform(x_train)
x_ss_test=ss.transform(x_test)

In [715]:
model=LogisticRegression()
model.fit(x_ss_train,y_train)

LogisticRegression()

In [716]:
predict_prob=model.predict_proba(x_ss_test)

In [717]:
new_customer_scaled=pd.DataFrame({"credit_lines_outstanding": [2],"loan_amt_outstanding": [5000],"total_debt_outstanding": [9000],"income": [65000],"years_employed": [4],"fico_score": [620]
})

In [718]:
st_nc=ss.transform(new_customer_scaled)

In [719]:
pr=model.predict_proba(st_nc)[:,1]
print(pr)

[0.00026277]

In [720]:
print(pr)

[0.00026277]

In [721]:
def CheckForNewCustomer(new_customer):
    nc=new_customer.copy()
    ss_new_customer=ss.transform(new_customer)
    customer=model.predict_proba(ss_new_customer)[:,1]
    cus=pd.DataFrame(customer,columns=['Default in Percent'])
    cusb=pd.DataFrame(customer.round(),columns=['Default 0/1'])
    return pd.concat([nc,cus,cusb],axis=1)

## Made a function for the prediction of customer default or not

In [722]:
new_customers = pd.DataFrame({
    "credit_lines_outstanding": [0, 2, 4, 1, 5],
    "loan_amt_outstanding": [1500, 5000, 9000, 3000, 10500],
    "total_debt_outstanding": [2000, 9000, 25000, 4500, 42000],
    "income": [120000, 65000, 35000, 85000, 25000],
    "years_employed": [10, 4, 2, 7, 1],
    "fico_score": [820, 620, 550, 720, 450]
})

In [723]:
CheckForNewCustomer(new_customer=new_customers)

,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,Default in Percent,Default 0/1
0,0,1500,2000,120000,10,820,0.0000,0.0000
1,2,5000,9000,65000,4,620,0.0003,0.0000
2,4,9000,25000,35000,2,550,1.0000,1.0000
3,1,3000,4500,85000,7,720,0.0000,0.0000
4,5,10500,42000,25000,1,450,1.0000,1.0000